brain.pals = list(
  dkt  = c(`banks superior temporal`	= "#196428ff",
           `caudal anterior cingulate`	= "#7D64A0ff",
           `caudal middle frontal`	= "#641900ff",
           cuneus	= "#DC1464ff",
           entorhinal	= "#DC140Aff",
           fusiform	= "#B4DC8Cff",
           `inferior parietal`	= "#DC3CDCff",
           `inferior temporal`	= "#B42878ff",
           `isthmus cingulate`	= "#8C148Cff",
           lateraloccipital	= "#141E8Cff",
           `lateralorbito frontal`	= "#234B32ff",
           lingual	= "#E18C8Cff",
           `medial orbito frontal`	= "#C8234Bff",
           `middle temporal`	= "#A06432ff",
           parahippocampal	= "#14DC3Cff",
           `para central`	= "#3CDC3Cff",
           `pars opercularis`	= "#DCB48Cff",
           `pars orbitalis`	= "#146432ff",
           `pars triangularis`	= "#DC3C14ff",
           pericalcarine	= "#78643Cff",
           `post central`	= "#DC1414ff",
           `posterior cingulate`	= "#DCB4DCff",
           `pre central`	= "#3C14DCff",
           precuneus	= "#A08CB4ff",
           `rostral anterior cingulate`	= "#50148Cff",
           `rostral middle frontal`	= "#4B327Dff",
           `superior frontal`	= "#14DCA0ff",
           `superior parietal`	= "#14B48Cff",
           `superior temporal`	= "#8CDCDCff",
           supramarginal	= "#50A014ff",
           `frontal pole`	= "#640064ff",
           `temporal pole`	= "#464646ff",
           `transverse temporal`	= "#9696C8ff",
           insula	= "#FFC020ff"
  ),
  yeo7 = c(visual = "#a153a2ff",
           somatomotor = "#6fabd2ff",
           `dorsal attention`= "#2c8b4bff",
           `ventral attention` = "#b77fb4ff",
           limbic = "#e7edcaff",
           frontoparietal = "#edaf5eff",
           default = "#e27283ff"
  ),
  yeo17 = c(`visual peripheral` = "#762284ff",
            `visual central` = "#fc2a1cff",
            `somatomotor A` = "#4984b2ff",
            `somatomotor B` = "#36cca5ff",
            `dorsal attention A` = "#4d9a42ff",
            `dorsal attention B` = "#0d7418ff",
            `ventral attention` = "#c145f6ff",
            `salience` = "#fd9bd4ff",
            `limbic A` = "#ddf7a9ff",
            `limbic B` = "#798639ff",
            `control C` = "#778dafff",
            `control A` = "#e39333ff",
            `control B` = "#86334aff",
            `default D` = "#143efaff",
            `default C` = "#041b80ff",
            `default A` = "#fff937ff",
            `default B` = "#cb4051ff"
  ),
  aseg =  c(amygdala	= "#67FFFFff",
            caudate	= "#7ABADCff",
            hippocampus	= "#DCD814ff",
            `lateral ventricle`	= "#781286ff",
            pallidum	= "#0D30FFff",
            putamen	= "#EC0DB0ff",
            `thalamus proper`	= "#00760Eff",
            `ventral DC`	= "#A52A2Aff"
  ),
  midsagittal = c(`3rd ventricle` =	"#CCB68Eff",
                  `4th ventricle` =	"#2ACCA4ff",
                  `brain stem` = "#779FB0ff",
                  `CC anterior` ="#0000FFff",
                  `CC central` = "#0000A0ff",
                  `CC mid anterior`	= "#0000D0ff",
                  `CC mid posterior` = "#000070ff",
                  `CC posterior` = "#000040ff",
                  `cerebellum cortex`	= "#E69422ff",
                  `cerebellum white matter`	= "#DCF8A4ff",
                  `cerebral cortex`	= "#CD3E4Eff"
  ),
  tracula = c(fmajor	= "#CC6666ff",
              fminor	= "#CC6666ff",
              atr	= "#FFFF66ff",
              cab	= "#99CC00ff",
              ccg	= "#009999ff",
              cst	= "#CC99FFff",
              ilf	= "#FF9933ff",
              slfp =	"#CCCCCCff",
              slft	= "#99FFFFff",
              unc	= "#6699FFff"
  )
)
save(brain.pals, file="data/brain.pals.RData",
     compress = "bzip2")

brain.pal.info <- data.frame(atlas=names(unlist(lapply(brain.pals,length))),
                             maxcol=unname(unlist(lapply(brain.pals,length))),
                             category="qual",
                             colorblind=FALSE)
save(brain.pal.info, file="data/brain.pal.info.RData",
     compress = "bzip2")

