brain_pals = list(
  dkt  = c(`banks superior temporal`	= "#196428",
           `caudal anterior cingulate`	= "#7D64A0",
           `caudal middle frontal`	= "#641900",
           cuneus	= "#DC1464",
           entorhinal	= "#DC140A",
           fusiform	= "#B4DC8C",
           `inferior parietal`	= "#DC3CDC",
           `inferior temporal`	= "#B42878",
           `isthmus cingulate`	= "#8C148C",
           `lateral occipital`	= "#141E8C",
           `lateral orbitofrontal`	= "#234B32",
           lingual	= "#E18C8C",
           `medial orbito frontal`	= "#C8234B",
           `middle temporal`	= "#A06432",
           parahippocampal	= "#14DC3C",
           `para central`	= "#3CDC3C",
           `pars opercularis`	= "#DCB48C",
           `pars orbitalis`	= "#146432",
           `pars triangularis`	= "#DC3C14",
           pericalcarine	= "#78643C",
           `post central`	= "#DC1414",
           `posterior cingulate`	= "#DCB4DC",
           `pre central`	= "#3C14DC",
           precuneus	= "#A08CB4",
           `rostral anterior cingulate`	= "#50148C",
           `rostral middle frontal`	= "#4B327D",
           `superior frontal`	= "#14DCA0",
           `superior parietal`	= "#14B48C",
           `superior temporal`	= "#8CDCDC",
           supramarginal	= "#50A014",
           `frontal pole`	= "#640064",
           `temporal pole`	= "#464646",
           `transverse temporal`	= "#9696C8",
           insula	= "#FFC020"
  ),
  aseg =  c(amygdala	= "#67FFFF",
            caudate	= "#7ABADC",
            hippocampus	= "#DCD814",
            `lateral ventricle`	= "#781286",
            pallidum	= "#0D30FF",
            putamen	= "#EC0DB0",
            `thalamus proper`	= "#00760E",
            `ventral DC`	= "#A52A2A"
  )
)

usethis::use_data(brain_pals,
                  internal = FALSE, overwrite = TRUE, compress="xz")


