# sf-optional brain renderer over flat polygon data ----
#
# Renders a brain atlas using ggplot2::geom_polygon over the polygon
# representation from ggseg.formats::atlas_polygons() (see ggseg.formats). No
# sf objects, no GDAL/GEOS/PROJ system libraries needed — enables wasm and
# air-gapped builds. First piece of Epic ggsegverse/ggseg#128.
#
# Scope of this iteration: simple per-view stacking from the polygons'
# pre-positioned coordinates. position_brain_sf() is not yet wired up for
# the polygon path; users wanting custom layouts should keep using
# geom_brain_sf() for now.

#' Plot brain atlas regions from the polygon representation (sf-optional)
#'
#' Renders a `ggseg_atlas` via `ggplot2::geom_polygon` using the polygon
#' representation from `ggseg.formats::atlas_polygons()`. Works on any atlas;
#' a polygon-backed atlas (e.g. from `ggseg.formats::as_polygon_atlas()`)
#' renders without requiring the `sf` package or its GDAL/GEOS/PROJ system
#' libraries.
#'
#' Hole geometry round-trips correctly via the `subgroup` aesthetic
#' (`grid::pathGrob` even-odd fill).
#'
#' @param mapping Set of aesthetic mappings created by `ggplot2::aes()`.
#' @param data A data.frame containing variables to map. If `NULL`, the
#'   atlas is plotted without user data.
#' @param atlas A `ggseg_atlas` object with 2D geometry (sf or polygons).
#' @param hemi Character vector of hemispheres to include.
#' @param view Character vector of views to include.
#' @param position Position adjustment. Defaults to [position_brain_polygon()],
#'   which lays views out horizontally without sf. Pass `"identity"` to use
#'   the polygons' raw coordinates. Per-view zoom is controlled here via
#'   [position_brain_polygon()]'s `zoom` argument.
#' @param context Logical. When `TRUE` (default), context regions (atlas rows
#'   with no `region` label, drawn grey) are kept. When `FALSE`, they are
#'   dropped so only true atlas regions are plotted.
#' @param show.legend Logical. Should this layer be included in legends?
#' @param inherit.aes Logical. If `FALSE`, overrides the default aesthetics.
#' @param ... Additional arguments passed to `ggplot2::geom_polygon()`.
#'
#' @return A list of ggplot2 layer and coord objects.
#' @keywords internal
#' @noRd
#' @importFrom ggplot2 aes layer scale_fill_manual
#' @importFrom rlang .data
#'
#' @examples
#' \dontrun{
#' library(ggplot2)
#' poly <- ggseg.formats::as_polygon_atlas(dk())
#' ggplot() + geom_brain_polygon(atlas = poly)
#' }
geom_brain_polygon <- function(
  mapping = aes(),
  data = NULL,
  atlas,
  hemi = NULL,
  view = NULL,
  position = position_brain_polygon(),
  context = TRUE,
  fun = mean,
  geom = GeomBrain,
  show.legend = NA,
  inherit.aes = TRUE,
  ...
) {
  # x/y/group/subgroup are generated by StatBrain from the atlas geometry:
  # `group` is the polygon feature id (ring grouping and draw order) and
  # `subgroup` marks holes. A user mapping for any of them would corrupt the
  # rendering, so we warn and drop it rather than honour the override.
  reserved <- intersect(names(mapping), c("x", "y", "group", "subgroup"))
  if (length(reserved)) {
    cli::cli_warn(c(
      "Ignoring the {.field {reserved}} aesthetic{?s} in {.arg mapping}.",
      "i" = paste(
        "{.fn geom_brain} sets {.field x}, {.field y}, {.field group}, and",
        "{.field subgroup} from the atlas geometry."
      )
    ))
    mapping <- as.list(mapping)[setdiff(names(mapping), reserved)]
    class(mapping) <- "uneval"
  }

  dots <- list(...)

  # check.aes = FALSE because LayerBrain injects non-standard "aesthetics"
  # (region/label/hemi/view) that the geom does not know about. The tradeoff is
  # that an aesthetic typo like aes(fil = x) is no longer caught here.
  brain_layer <- layer(
    geom = geom,
    # StatBrain lives in R/stat-brain.R; lintr can't resolve the cross-file
    # ggproto object statically (R CMD check does).
    stat = StatBrain, # nolint: object_usage_linter.
    data = data,
    mapping = mapping,
    position = "identity",
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = c(list(fun = fun, na.rm = FALSE), dots),
    layer_class = LayerBrain,
    check.aes = FALSE,
    check.param = FALSE
  )
  # The atlas and layout config ride on the layer object so LayerBrain's
  # setup_layer() can flatten it and hand it to StatBrain at plot-build time
  # (after inheriting top-level data/aes), rather than eagerly at construction.
  brain_layer$brain_atlas <- atlas
  brain_layer$brain_hemi <- hemi
  brain_layer$brain_view <- view
  brain_layer$brain_position <- position
  brain_layer$brain_context <- context

  # geom_brain() plots your data on the brain; it does not colour the atlas by
  # its own palette. Regions you supply no value for stay grey (GeomBrain's
  # default fill). For a palette-coloured atlas overview use `plot(atlas)`
  # (ggseg.formats), or map it yourself with `aes(fill = region)` and
  # `scale_fill_brain()`.
  list(brain_layer, coord_brain())
}


# ggplot2 does not export `Layer`, so we reach into its namespace once
# to get the parent ggproto. Using `getFromNamespace()` rather than `:::`
# keeps `R CMD check` clean. Defined here (the canonical polygon path)
# because this file is sourced before layer-brain.R, whose `LayerBrainSf`
# also subclasses it.
ggplot2_Layer <- function() {
  utils::getFromNamespace("Layer", "ggplot2")
}

#' @section GeomBrain ggproto:
#' `GeomBrain` is the [ggplot2::Geom] ggproto that renders brain atlas polygons.
#' It subclasses [ggplot2::GeomPolygon] and supplies the brain defaults through
#' `default_aes` -- outline `colour` (grey35), `linewidth` (0.2), and `fill`
#' (grey) -- which apply when the user has not mapped those aesthetics but yield
#' to a mapping when present (ggsegverse/ggseg#160). The grey default fill is
#' why an atlas plotted without data renders grey, not palette-coloured. Used
#' internally by [geom_brain()]; not typically called directly.
#'
#' @export
#' @rdname ggbrain
#' @order 2
#' @usage NULL
#' @format NULL
#' @importFrom ggplot2 ggproto GeomPolygon aes
GeomBrain <- ggproto(
  "GeomBrain",
  GeomPolygon,
  default_aes = utils::modifyList(
    GeomPolygon$default_aes,
    aes(colour = "grey35", linewidth = 0.2, fill = "grey")
  )
)

#' Custom ggplot2 Layer for the (default) sf-optional polygon path
#'
#' The canonical brain layer. Its `setup_layer()` runs at plot-build time, so it
#' inherits the top-level `data` and aesthetic mapping. It flattens the atlas
#' into the `flat` geometry and hands it to [StatBrain] (via `stat_params`),
#' which joins and aggregates the user data per facet panel -- so faceting
#' replicates the whole atlas natively, with no grouped-data-frame replication.
#' The user data itself is passed through untouched (join keys are injected as
#' aesthetics so they survive into the stat); when no data is supplied the
#' atlas's own identity rows drive the stat so the bare atlas still renders (and
#' `aes(fill = region)` / faceting on an atlas column keep working). Fixes
#' ggsegverse/ggseg#158 (top-level `aes()`/`data` were dropped by the eager
#' build). The deprecated sf renderer has a parallel [LayerBrainSf].
#'
#' @keywords internal
#' @noRd
#' @importFrom ggplot2 ggproto ggproto_parent
LayerBrain <- ggproto(
  "LayerBrain",
  ggplot2_Layer(),
  setup_layer = function(self, data, plot) {
    dt <- ggproto_parent(ggplot2_Layer(), self)$setup_layer(data, plot)

    atlas <- self$brain_atlas
    if (is.null(atlas)) {
      cli::cli_abort(
        "No atlas supplied, please provide a brain atlas to the geom."
      )
    }

    has_data <- !inherits(dt, "waiver") && is.data.frame(dt) && nrow(dt) > 0

    zoom_spec <- if (is_polygon_position(self$brain_position)) {
      self$brain_position$zoom
    } else {
      NULL
    }
    focus <- resolve_zoom_focus(zoom_spec, if (has_data) dt else NULL, atlas)

    flat <- prepare_polygon_atlas(
      atlas,
      hemi = self$brain_hemi,
      view = self$brain_view,
      position = self$brain_position,
      context = self$brain_context,
      focus = focus
    )

    # All atlas metadata columns (region/label/hemi/view/lobe/... whatever the
    # core carries), derived from flat so no atlas column is missed.
    atlas_cols <- atlas_metadata_cols(flat)

    if (!has_data) {
      # No user data: drive the stat with the atlas's own identity rows so its
      # columns are available for aesthetics like aes(fill = region) and for
      # faceting on an atlas column; the atlas draw order is preserved (reorder
      # off).
      dt <- unique(flat[, atlas_cols, drop = FALSE])
    }

    keys <- intersect(brain_join_keys(), intersect(names(dt), names(flat)))
    if (length(keys) == 0) {
      cli::cli_abort(c(
        "{.arg data} has no columns in common with the atlas.",
        "i" = paste0(
          "Need {.field region} or {.field label} ",
          "(and optionally {.field hemi})."
        )
      ))
    }
    if (has_data) {
      warn_unmatched_polygon_data(dt, flat, keys)
    }

    # Faceting on an atlas column (e.g. hemi, view) subsets the atlas per panel,
    # the way the old renderer did; faceting on a user column replicates it.
    # StatBrain handles the subset, so those columns must also survive into it.
    facet_atlas_cols <- intersect(
      plot$facet$vars(),
      intersect(atlas_cols, names(dt))
    )

    # Join keys and any atlas facet columns must be aesthetics to survive
    # compute_aesthetics() and reach StatBrain (see R/stat-brain.R).
    for (k in union(keys, facet_atlas_cols)) {
      if (is.null(self$computed_mapping[[k]])) {
        self$computed_mapping[[k]] <- as.name(k)
      }
    }

    self$stat_params$flat <- flat
    # Draw-order-follows-data (#162) only applies to real user data; keep the
    # atlas order when the driving rows are just the atlas identity.
    self$stat_params$reorder <- has_data
    self$stat_params$facet_atlas_cols <- facet_atlas_cols

    dt
  }
)


#' Auto-group user data by facet variables for atlas replication (sf path)
#'
#' Used only by the deprecated sf [LayerBrainSf]: when data is faceted but not
#' explicitly grouped, group it by the facet variables so [brain_join()]
#' replicates the full atlas once per panel. The default polygon path no longer
#' needs this -- [StatBrain] regenerates the atlas per panel natively. Facet
#' variables that are atlas identity columns (e.g. `hemi`, `view`) are excluded:
#' faceting on those subsets the atlas rather than replicating it.
#'
#' @keywords internal
#' @noRd
group_by_facet_vars <- function(data, plot, atlas) {
  facet_vars <- plot$facet$vars()
  group_vars <- intersect(facet_vars, names(data))
  atlas_cols <- unique(c(
    names(atlas$core),
    "view",
    "type",
    "atlas",
    "hemi"
  ))
  group_vars <- setdiff(group_vars, atlas_cols)
  if (length(group_vars) > 0) {
    data <- dplyr::group_by(data, dplyr::across(dplyr::all_of(group_vars)))
  }
  data
}


#' Flatten a polygon atlas into a row-per-point data.frame for geom_polygon
#'
#' Unnests `ggseg.formats::atlas_polygons(atlas)`, joins with `atlas$core`,
#' applies optional
#' hemi/view filters, and adds the `.feature_id` helper column that the
#' polygon renderer maps to `group` so each (label, view, group) polygon
#' piece renders as one ring set.
#'
#' @keywords internal
#' @noRd
prepare_polygon_atlas <- function(
  atlas,
  hemi = NULL,
  view = NULL,
  position = NULL,
  context = TRUE,
  focus = NULL
) {
  if (is.null(ggseg.formats::atlas_geom(atlas))) {
    cli::cli_abort(c(
      "{.arg atlas} has no 2D geometry.",
      "i" = "Provide an atlas with {.field geom} (sf or polygons) in its data."
    ))
  }

  flat <- tidyr::unnest(
    ggseg.formats::atlas_polygons(atlas),
    cols = "geometry"
  )
  # Namespace the polygon-ring grouping as `.group` before joining `core`:
  # some atlases (e.g. tracula) carry their own `group` column in `core`,
  # which would otherwise collide and suffix this one away.
  names(flat)[names(flat) == "group"] <- ".group"
  flat <- dplyr::left_join(
    flat,
    atlas$core,
    by = "label",
    relationship = "many-to-many"
  )

  if (!is.null(view)) {
    avail <- unique(flat$view)
    invalid <- setdiff(view, avail)
    if (length(invalid)) {
      cli::cli_abort(
        "Invalid view(s): {.val {invalid}}. Available: {.val {avail}}"
      )
    }
    flat <- flat[flat$view %in% view, , drop = FALSE]
  }

  if (!is.null(hemi)) {
    avail <- unique(flat$hemi)
    invalid <- setdiff(hemi, avail)
    if (length(invalid)) {
      cli::cli_abort(
        "Invalid hemisphere(s): {.val {invalid}}. Available: {.val {avail}}"
      )
    }
    flat <- flat[flat$hemi %in% hemi, , drop = FALSE]
  }

  if (!context && "region" %in% names(flat)) {
    flat <- flat[!is.na(flat$region), , drop = FALSE]
  }

  flat$atlas <- atlas$atlas
  flat$type <- atlas$type

  if (atlas$type == "cortical") {
    if (!"hemi" %in% names(flat)) {
      flat$hemi <- NA_character_
    }
    missing_hemi <- is.na(flat$hemi)
    flat$hemi[missing_hemi] <- dplyr::case_when(
      grepl("^lh[_.]", flat$label[missing_hemi]) ~ "left",
      grepl("^rh[_.]", flat$label[missing_hemi]) ~ "right",
      .default = NA_character_
    )
  }

  # Draw order follows row order: feature ids increase in the order features
  # first appear in the atlas (levels = unique), not alphabetically. When user
  # data is joined, StatBrain reassigns these to follow the data's row order
  # (see ggsegverse/ggseg#162). Lower id = drawn first (underneath).
  feature_key <- paste(flat$label, flat$view, flat$.group, sep = "@@")
  flat$.feature_id <- as.integer(factor(
    feature_key,
    levels = unique(feature_key)
  ))

  if (is_polygon_position(position)) {
    flat <- frame_2_position_flat(
      flat,
      position$position,
      nrow = position$nrow,
      ncol = position$ncol,
      views = position$views,
      focus = focus,
      zoom_pad = if (is.null(position$zoom_pad)) 0.05 else position$zoom_pad
    )
  }

  flat
}


#' Warn about user data rows that match no atlas region
#'
#' The polygon join keeps every atlas polygon and drops unmatched user rows
#' (e.g. a mistyped or renamed region), so a mismatch would otherwise vanish
#' silently. This mirrors the sf-path [brain_join()] warning so the dropped rows
#' are surfaced (ggsegverse/ggseg#121). Grouping columns are ignored when
#' detecting matches -- only the `by` keys (region/label/hemi) decide a match --
#' so the unmatched rows are reported once across all groups.
#'
#' @param data The user data.frame (possibly grouped) being joined.
#' @param flat The flattened atlas rows joined against.
#' @param by Character vector of join columns.
#' @return `invisible(NULL)`, called for its warning side effect.
#' @keywords internal
#' @noRd
warn_unmatched_polygon_data <- function(data, flat, by) {
  unmatched <- dplyr::anti_join(dplyr::ungroup(data), flat, by = by)
  if (nrow(unmatched) == 0) {
    return(invisible(NULL))
  }
  cli::cli_warn(c(
    "Some data not merged properly.",
    "i" = "Check for naming errors in {.arg data}:",
    " " = paste(
      utils::capture.output(print(dplyr::as_tibble(unmatched))),
      collapse = "\n"
    )
  ))
  invisible(NULL)
}
