utils::globalVariables(c("area",
                         "atlas",
                         "colour",
                         "group",
                         "hemi",
                         "lat",
                         "long",
                         "side",
                         "x"))
