# StatBrain: per-panel join + aggregation over the flat polygon atlas ----
#
# The brain's *shape* is generated by the atlas geometry, not supplied by the
# user, so StatBrain follows the geometry-generating stat pattern (cf.
# ggplot2::StatSf): it requires no positional aesthetics and instead emits the
# full atlas geometry from a prepared `flat` data.frame handed to it by
# LayerBrain (see R/geom-brain-polygon.R). Running as a Stat means ggplot2
# computes it once per panel, so faceting replicates the whole atlas natively --
# no manual grouped-data replication needed. Multiple user rows for the same
# region are collapsed with `fun` (default mean) before the join.

#' @section StatBrain ggproto:
#' `StatBrain` is the [ggplot2::Stat] that powers [geom_brain()] and
#' [stat_brain()]. Its `compute_panel()` receives one facet panel's user data,
#' aggregates the mapped values per atlas region with `fun`, and joins them onto
#' the full atlas geometry -- so every region renders in every panel whether or
#' not you supplied a value for it. You rarely reference it directly; use it via
#' `geom_brain(..., stat = StatBrain)` or [stat_brain()] when building a custom
#' layer.
#'
#' @export
#' @rdname ggbrain
#' @order 3
#' @usage NULL
#' @format NULL
#' @importFrom ggplot2 ggproto Stat
StatBrain <- ggproto(
  "StatBrain",
  Stat,
  required_aes = character(0),
  retransform = TRUE,
  extra_params = c("na.rm", "fun", "flat", "reorder", "facet_atlas_cols"),
  # `na.rm` is the standard stat switch for dropping missing values (used by the
  # base `Stat$compute_layer()`'s `remove_missing()`); it does NOT touch
  # aggregation. To drop NAs while aggregating, pass e.g.
  # `fun = \(x) mean(x, na.rm = TRUE)`.
  compute_panel = function(
    data,
    scales,
    flat = NULL,
    fun = mean,
    reorder = TRUE,
    facet_atlas_cols = character(0),
    na.rm = FALSE
  ) {
    if (is.null(flat)) {
      cli::cli_abort(c(
        "{.cls StatBrain} needs a prepared atlas geometry.",
        "i" = "Build the layer with {.fn geom_brain} or {.fn stat_brain}."
      ))
    }
    # Faceting on an atlas-intrinsic column (e.g. hemi, view) subsets the atlas
    # per panel rather than replicating it; faceting on a user column replicates
    # the whole atlas. This mirrors the pre-StatBrain contract.
    flat <- subset_flat_to_facet(flat, data, facet_atlas_cols)
    join_brain_values(data, flat, fun, reorder = reorder)
  }
)


#' Stat-first constructor for a brain atlas layer
#'
#' The stat-first spelling of [geom_brain()]. Both build the same layer -- a
#' [StatBrain] that aggregates and joins your data onto the atlas geometry,
#' drawn by `geom`. Reach for `stat_brain()` when you want to pair [StatBrain]
#' with a different geom (e.g. a custom polygon geom); otherwise [geom_brain()]
#' is the friendlier entry point.
#'
#' @inheritParams geom_brain
#' @param geom The geometric object used to render the atlas. Defaults to
#'   [GeomBrain].
#'
#' @return A list of ggplot2 layer and coord objects.
#' @seealso [geom_brain()]
#' @export
#' @importFrom ggplot2 aes
#' @examples
#' library(ggplot2)
#'
#' # Equivalent to geom_brain(atlas = dk())
#' ggplot() +
#'   stat_brain(atlas = dk())
stat_brain <- function(
  mapping = aes(),
  data = NULL,
  atlas,
  hemi = NULL,
  view = NULL,
  position = position_brain(),
  context = TRUE,
  fun = mean,
  geom = GeomBrain,
  show.legend = NA,
  inherit.aes = TRUE,
  ...
) {
  geom_brain_polygon(
    mapping = mapping,
    data = data,
    atlas = atlas,
    hemi = hemi,
    view = view,
    position = position,
    context = context,
    fun = fun,
    geom = geom,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    ...
  )
}


#' The columns `geom_brain()` joins user data to the atlas on
#'
#' The single source of truth for the join keys, deliberately a subset of the
#' atlas metadata columns.
#' @keywords internal
#' @noRd
brain_join_keys <- function() {
  c("region", "label", "hemi")
}


#' Atlas metadata columns of a flattened atlas
#'
#' Every column of `flat` except the polygon geometry and internal bookkeeping,
#' i.e. the columns that identify a region/slice (`region`, `label`, `hemi`,
#' `view`, and whatever else the atlas core carries, e.g. `lobe`). Derived from
#' `flat` so no atlas column is missed by a hardcoded list.
#' @keywords internal
#' @noRd
atlas_metadata_cols <- function(flat) {
  setdiff(names(flat), c("x", "y", ".group", "subgroup", ".feature_id"))
}


#' Aggregate user values per atlas region and join onto the flat atlas
#'
#' The heart of [StatBrain]'s `compute_panel()`. Collapses the panel's user rows
#' to one row per join key with [aggregate_brain_values()], left-joins them onto
#' the full atlas geometry so unmatched regions keep `NA` (drawn grey by the
#' fill scale's `na.value`), and reassigns the polygon draw order to the user
#' data row order (ggsegverse/ggseg#162). With no join keys (no user data) it
#' returns the atlas geometry unchanged.
#'
#' @param data One facet panel's user data, with computed aesthetics.
#' @param flat The flattened atlas geometry from [prepare_polygon_atlas()].
#' @param fun Aggregating function applied to numeric aesthetics per region.
#' @param reorder When `TRUE`, reassign the polygon draw order to follow the
#'   data row order (ggsegverse/ggseg#162). Set `FALSE` when the data is just
#'   the atlas's own identity rows (no user data), so the atlas draw order is
#'   preserved.
#' @return `flat` with joined (aggregated) values and `group` set to the polygon
#'   feature id.
#' @keywords internal
#' @noRd
#' @importFrom rlang .data
join_brain_values <- function(data, flat, fun, reorder = TRUE) {
  keys <- intersect(brain_join_keys(), intersect(names(data), names(flat)))

  if (length(keys) == 0) {
    flat$group <- flat$.feature_id
    return(flat)
  }

  agg <- aggregate_brain_values(data, keys, fun, atlas_metadata_cols(flat))
  joined <- dplyr::left_join(flat, agg, by = keys, suffix = c("", ".user"))
  if (reorder) {
    joined <- order_features_by_data(joined, data, keys)
  }
  joined$group <- joined$.feature_id
  joined
}


#' Collapse multiple rows per region to one aggregated row
#'
#' Groups the user data by the join keys and reduces every other aesthetic
#' column to a single value: numeric columns (e.g. a mapped `fill` value) with
#' `fun`, non-numeric columns to their first value. Atlas columns (already on
#' `flat`) and ggplot2 bookkeeping columns are left out of the aggregation. This
#' is what lets `geom_brain()` accept long data with several rows per region
#' (e.g. one per subject) and draw a single summarised value.
#'
#' @param data The user data for one panel, with computed aesthetics.
#' @param keys Character vector of join-key columns to group by.
#' @param fun Aggregating function for numeric aesthetic columns.
#' @param atlas_cols The atlas metadata columns (from [atlas_metadata_cols()]);
#'   any `data` column among them is geometry, not a value to aggregate.
#' @return One row per unique key combination.
#' @keywords internal
#' @noRd
aggregate_brain_values <- function(data, keys, fun, atlas_cols) {
  ignore <- c(
    "group",
    "PANEL",
    "flipped_aes",
    intersect(names(data), atlas_cols)
  )
  value_cols <- setdiff(names(data), ignore)

  grouped <- dplyr::group_by(data, dplyr::across(dplyr::all_of(keys)))
  tryCatch(
    dplyr::summarise(
      grouped,
      dplyr::across(
        dplyr::all_of(value_cols),
        function(col) if (is.numeric(col)) fun(col) else col[[1]]
      ),
      .groups = "drop"
    ),
    error = function(cnd) {
      cli::cli_abort(
        c(
          "{.arg fun} must reduce each region's values to a single value.",
          "i" = "It returned the wrong length for at least one region.",
          "i" = "Try {.fn mean} (the default), {.fn median}, or {.fn max}."
        ),
        parent = cnd
      )
    }
  )
}


#' Subset the atlas geometry to a facet panel's atlas-column values
#'
#' Faceting on an atlas-intrinsic column (`hemi`, `view`, ...) should draw only
#' that slice of the atlas in each panel, the way the pre-StatBrain renderer did
#' by returning the faceted atlas. `facet_atlas_cols` lists the facet variables
#' that are atlas columns (resolved in `LayerBrain$setup_layer()`); this keeps
#' the `flat` rows whose values match the panel's. Faceting on a user column
#' passes an empty `facet_atlas_cols`, so the whole atlas is kept per panel.
#'
#' @param flat The flattened atlas geometry.
#' @param data One facet panel's data.
#' @param facet_atlas_cols Atlas columns that are also facet variables.
#' @return `flat`, filtered to the panel's atlas-column values.
#' @keywords internal
#' @noRd
subset_flat_to_facet <- function(flat, data, facet_atlas_cols) {
  for (col in facet_atlas_cols) {
    if (col %in% names(data) && col %in% names(flat)) {
      flat <- flat[flat[[col]] %in% unique(data[[col]]), , drop = FALSE]
    }
  }
  flat
}


#' Order `.feature_id` by the user data row order so draw order follows it
#'
#' [ggplot2::GeomPolygon] paints features in ascending `group` (here
#' `.feature_id`) order, so lower ids draw first (underneath) and higher ids on
#' top. This orders the `.feature_id` levels by the order each region first
#' appears in `data`, so users control layering with [dplyr::arrange()] (later
#' rows on top). Regions absent from `data` keep the atlas order underneath.
#' ggplot2 handles the actual sorting and drawing; this only sets the group ids
#' it sorts on (see ggsegverse/ggseg#162).
#'
#' Because [StatBrain] runs per panel, `data` here is already just that panel's
#' rows, so each facet lays out in its own data order.
#'
#' @param flat Joined flat polygon data with `label`, `view`, `.group` and the
#'   `by` columns.
#' @param data The user data.frame the features were joined against.
#' @param by Character vector of join columns.
#' @return `flat` with `.feature_id` reassigned to follow the data order.
#' @keywords internal
#' @noRd
order_features_by_data <- function(flat, data, by) {
  paste_cols <- function(df, cols) {
    do.call(
      paste,
      c(lapply(cols, function(col) as.character(df[[col]])), sep = "@@")
    )
  }

  data_rank <- match(paste_cols(flat, by), unique(paste_cols(data, by)))
  data_rank[is.na(data_rank)] <- 0L

  feature_key <- paste_cols(flat, c("label", "view", ".group"))
  first_feature <- !duplicated(feature_key)
  # order() is stable, so features with the same rank (context regions, or the
  # rings of one region) keep their atlas appearance order.
  ordered_levels <- feature_key[first_feature][
    order(data_rank[first_feature])
  ]

  flat$.feature_id <- as.integer(factor(feature_key, levels = ordered_levels))
  flat
}
