on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: code-quality

permissions:
  contents: read
  pull-requests: write

jobs:
  code-quality:
    uses: ggsegverse/.github/.github/workflows/code-quality.yaml@main
    secrets: inherit
