on:
  push:
    branches: [main, master]
  pull_request:

name: formats-compat.yaml

permissions: read-all

jobs:
  formats-compat:
    uses: ggsegverse/.github/.github/workflows/formats-compat.yaml@main
