on:
  release:
    types: [published]

name: neuroconductor-release

permissions:
  contents: write

jobs:
  neuroconductor:
    uses: ggsegverse/.github/.github/workflows/neuroconductor-release.yaml@main
    secrets: inherit
