on:
  push:
    branches: [main, master]
    paths: [DESCRIPTION]
  workflow_dispatch: # manual trigger, e.g. to backfill a missed release

name: release-on-version.yaml

permissions:
  contents: write

jobs:
  release:
    uses: ggsegverse/.github/.github/workflows/release-on-version.yaml@main
