on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-coverage

permissions:
  contents: write

jobs:
  test-coverage:
    uses: ggsegverse/.github/.github/workflows/test-coverage.yaml@main
    secrets: inherit
