on:
  push:
    branches: [main, master]
    paths:
      - DESCRIPTION
      - .github/workflows/update-codemeta.yaml
  workflow_dispatch:

name: update-codemeta

permissions:
  contents: write
  pull-requests: write

jobs:
  update-codemeta:
    uses: ggsegverse/.github/.github/workflows/update-codemeta.yaml@main
    secrets: inherit
